### ISSUE TITLE
update_assets_version by date of last modified file

### ISSUE THREAD

**Issue by bigfoot90** [everzet/capifony#553]
This is a more advanced version of ```symfony:assets:update_version```

```ruby
task :update_version, :roles => :app, :except => { :no_release => true } do
    capifony_pretty_print "--> Updating `assets_version`"
    asset_paths = asset_children.map { |p| "#{latest_release}/#{p}" }.join(" ")
    file_path = "#{latest_release}/#{app_config_path}/assets_version.yml"
    assets_version = capture("find #{asset_paths} -type f -printf '%Ts\\n' | sort -n | tail -1")
    assets_version = assets_version.to_i.to_s(36)
    puts "    Latest assets version: (#{assets_version})"
    run "echo 'parameters:\\n    assets_version: #{assets_version}' > #{file_path}"
    capifony_puts_ok
end
```

It gets the date of last modified file in ```asset_children``` directories and generates a file containing
```yml
parameters:
    assets_version: nh9awc
```

and can be included in ```config.yml```
```yml
imports:
    - { resource: assets_version.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    ...
    templating:
        assets_version:       %assets_version%

...
```

This task must to be runned 
**after** ```symfony:composer:install``` or ```symfony:composer:update```
**after** ```symfony:assets:install``` or ```symfony:assetic:dump```
**before** ```symfony:cache:clear```
**before** normalizing assets timestaps.

Can I make a **PR**?
